RpgMvc/Controllers/DisputasController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RpgMvc.Models;

namespace RpgMvc.Controllers
{
    public class DisputasController : Controller
    {
        public string uriBase = "http://gdias.somee.com/RpgApi/Disputas/"; //chamar somee

        [HttpGet]
        public async Task<ActionResult> IndexAsync()
        {
            //(A) Criação da variável http e obtenção do token guardado na session
            HttpClient httpClient = new HttpClient();

            string token = HttpContext.Session.GetString("SessionTokenUsuario");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            //(B) Definição da rota da API que buscará a lista de personagens na API, retornando uma lista se o método
            string uriBuscaPersonagens = "http://gdias.somee.com/RpgApi/Personagem/GetAll";

            HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);

            string serialized = await response.Content.ReadAsStringAsync();

            /*(C) Se o status da requisição for 200 (Ok) então deserializamos para transformar numa lista de
            personagens, e depois geramos duas ViewBags a partir da lista de personagens, uma como os
            atacantes e outra como os oponentes. ViewsBags são maneiras de trafegar dados entre a controller e
            views e isso é que fará o carregamento do dropdownlist aparecer.*/

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                List<PersonagemViewModel> listaPersonagens = await Task.Run(() =>
                    JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));
                ViewBag.ListaAtacantes = listaPersonagens;
                ViewBag.ListaOponentes = listaPersonagens;
            }
            else
                TempData["MensagemErro"] = serialized; //(D) Mensagem de erro sendo enviado através do TempData. TempData é outra maneira de trafegar dados entre uma controller e uma View.
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> IndexAsync(DisputaViewModel disputa)
        {
            HttpClient httpClient = new HttpClient();
            
            string uriComplementar = "Arma";
            
            var content = new StringContent(JsonConvert.SerializeObject(disputa));
           
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            
            HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);
            
            string serialized = await response.Content.ReadAsStringAsync();
            
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                disputa = await Task.Run(() =>
                JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                TempData["Mensagem"] = disputa.Narracao;
            }
            else
                TempData["MensagemErro"] = serialized;
           
            return RedirectToAction("Index", "Personagens");
        }


        [HttpGet]
        public async Task<ActionResult> IndexHabilidadesAsync()
        {
            //(A) Criação da variável http e obtenção do token guardado na session
            HttpClient httpClient = new HttpClient();

            string token = HttpContext.Session.GetString("SessionTokenUsuario");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            //(B) Definição da rota da API que buscará a lista de personagens na API, retornando uma lista se o método
            string uriBuscaPersonagens = "http://gdias.somee.com/RpgApi/Personagem/GetAll";

            HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);

            string serialized = await response.Content.ReadAsStringAsync();

            /*(C) Se o status da requisição for 200 (Ok) então deserializamos para transformar numa lista de
            personagens, e depois geramos duas ViewBags a partir da lista de personagens, uma como os
            atacantes e outra como os oponentes. ViewsBags são maneiras de trafegar dados entre a controller e
            views e isso é que fará o carregamento do dropdownlist aparecer.*/

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                List<PersonagemViewModel> listaPersonagens = await Task.Run(() =>
                    JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));
                ViewBag.ListaAtacantes = listaPersonagens;
                ViewBag.ListaOponentes = listaPersonagens;
            }
            else
                TempData["MensagemErro"] = serialized; //(D) Mensagem de erro sendo enviado através do TempData. TempData é outra maneira de trafegar dados entre uma controller e uma View.


            string uriBuscaHabilidades = "http://gdias.somee.com/RpgApi/PersonagemHabilidades/GetHabilidades";

            response = await httpClient.GetAsync(uriBuscaHabilidades);

            serialized = await response.Content.ReadAsStringAsync();

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                List<HabilidadeViewModel> listaHabilidades = await Task.Run(() =>
                    JsonConvert.DeserializeObject<List<HabilidadeViewModel>>(serialized));
                ViewBag.ListaHabilidades = listaHabilidades;
            }
            else
                TempData["MensagemErro"] = serialized;

            return View("IndexHabilidades");
        }

    [HttpPost]
        public async Task<ActionResult> IndexHabilidadesAsync(DisputaViewModel disputa)
        {
            HttpClient httpClient = new HttpClient();

            string uriComplementar = "Habilidades";

            var content = new StringContent(JsonConvert.SerializeObject(disputa));

            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);

            string serialized = await response.Content.ReadAsStringAsync();

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                disputa = await Task.Run(() =>
                JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                TempData["Mensagem"] = disputa.Narracao;
            }
            else
                TempData["MensagemErro"] = serialized;

            return RedirectToAction("Index", "Personagens");
        }

    [HttpGet]
        public async Task<ActionResult> DisputaGeralAsync()
        {
            HttpClient httpClient = new HttpClient();

            string token = HttpContext.Session.GetString("SessionTokenUsuario");

            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            
            string uriBuscaPersonagens = "http://gdias.somee.com/RpgApi/Personagem/GetAll";
            
            HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);
            
            string serialized = await response.Content.ReadAsStringAsync();
            List<PersonagemViewModel> listaPersonagens = await Task.Run(() =>
                JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));
           
            string uriDisputa = "http://gdias.somee.com/RpgApi/Disputas/DisputaEmGrupo";
            
            DisputaViewModel disputa = new DisputaViewModel();
            disputa.ListaIdPersonagens = new List<int>();
            disputa.ListaIdPersonagens.AddRange(listaPersonagens.Select(p => p.Id));
           
            var content = new StringContent(JsonConvert.SerializeObject(disputa));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            response = await httpClient.PostAsync(uriDisputa, content);
            serialized = await response.Content.ReadAsStringAsync();
           
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                disputa = await Task.Run(() =>
                    JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                TempData["Mensagem"] = string.Join(" - ", disputa.Resultados);
            }
            else
                TempData["MensagemErro"] = serialized;

            return RedirectToAction("Index", "Personagens");
        }


    }
}

RpgMvc/Controllers/PersonagemHabilidadesController.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RpgMvc.Models;

namespace RpgMvc.Controllers
{
    public class PersonagemHabilidadesController : Controller
    {
        public string uriBase = "http://gdias.somee.com/RpgApi/PersonagemHabilidades/";
        
    
[HttpGet("PersonagemHabilidades/{id}")]
        public async Task<ActionResult> IndexAsync(int id)
        {
            HttpClient httpClient = new HttpClient();

            string token = HttpContext.Session.GetString("SessionTokenUsuario");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());

            string serialized = await response.Content.ReadAsStringAsync();

            List<PersonagemHabilidadesViewModel> lista = await Task.Run(() =>
                JsonConvert.DeserializeObject<List<PersonagemHabilidadesViewModel>>(serialized));
            
            return View(lista);
        }

[HttpGet]
        public async Task<ActionResult> DeleteAsync(int habilidadeId, int personagemId)
        {
            HttpClient httpClient = new HttpClient();
            string uriComplementar = "DeletePersonagemHabilidade";

            string token = HttpContext.Session.GetString("SessionTokenUsuario");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            PersonagemHabilidadesViewModel ph = new PersonagemHabilidadesViewModel();
            ph.HabilidadeId = habilidadeId;
            ph.PersonagemId = personagemId;

            var content = new StringContent(JsonConvert.SerializeObject(ph));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);

            string serialized = await response.Content.ReadAsStringAsync();

            if(response.StatusCode == System.Net.HttpStatusCode.OK)
                TempData["Mensagem"] = serialized;
            else
                TempData["MensagemErro"] = serialized;
            
            return RedirectToAction("Index", "Personagens");

             /*(A) Rota da API sendo guardada para concatenar com o endereço base
            (B) Recuperação do Token da sessão e armazenamento dela no httpClient
            (C) Objeto sendo preenchido pelo que foi passado nos parâmetros do método
            (D) Serialização do objeto e envio para a API de acordo com o endereço completo
            (E) Variável serialized para guardar a mensagem de retorno da API de acordo com sucesso (200) ou erro.
            (F) Redirecionamento para o Método Index da controller de Personagens*/ 
            
        }

[HttpGet]
        public async Task<ActionResult> Create(int id, string nome)
        {
            string uriComplementar = "GetHabilidades";
            HttpClient httpClient = new HttpClient();

            string token = HttpContext.Session.GetString("SessionTokenUsuario");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);

            string serialized = await response.Content.ReadAsStringAsync();
            List<HabilidadeViewModel> habilidades = await Task.Run(() =>
                JsonConvert.DeserializeObject<List<HabilidadeViewModel>>(serialized));
            
            ViewBag.ListaHabilidades = habilidades;

            PersonagemHabilidadesViewModel ph = new PersonagemHabilidadesViewModel();
            ph.Personagem = new PersonagemViewModel();
            ph.Habilidade = new HabilidadeViewModel();
            ph.PersonagemId = id;
            ph.Personagem.Nome = nome;

            return View(ph);
            
        }

[HttpPost]
        public async Task<ActionResult> CreateAsync(PersonagemHabilidadesViewModel ph)
        {
            HttpClient httpClient = new HttpClient();

            string token = HttpContext.Session.GetString("SessionTokenUsuario");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var content = new StringContent(JsonConvert.SerializeObject(ph));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = await httpClient.PostAsync(uriBase, content);

            string serialized = await response.Content.ReadAsStringAsync();

            if(response.StatusCode == System.Net.HttpStatusCode.OK)
                TempData["Mensagem"] = "Habilidade cadastrada com sucesso";
            else
                TempData["MensagemErro"] = serialized;
            
            return RedirectToAction("Index", "PersonagenmHabilidades", new {id = ph.PersonagemId});

        }

    }
}

RpgMvc/Views/Personagens/Create.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{ 
    ViewBag.Title = "Novo Personagem";
}
<h2>Criar um Novo Personagem</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Classe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.Classe , Html.GetEnumSelectList(typeof(RpgMvc.Models.Enuns.ClasseEnum)),
                    "----Selecione----", new { @class = "form-control"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Defesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Defesa, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
         <div class="form-group">
            @Html.LabelFor(model => model.PontosVida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.PontosVida, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
         <div class="form-group">
            @Html.LabelFor(model => model.Forca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Forca, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
         <div class="form-group">
            @Html.LabelFor(model => model.Inteligencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Inteligencia, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Retornar", "Index")
</div>

RpgMvc/Views/Personagens/Details.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Detalhes do Personagem";
}
<h2>Detalhes do Personagem</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>
        
        <dt>@Html.DisplayNameFor(model => model.Nome)</dt>
        <dd>@Html.DisplayFor(model => model.Nome)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id}) |
    @Html.ActionLink("Retornar", "Index")
</p>

RpgMvc/Views/Personagens/Edit.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Editar Personagem";
}
<h2>Editar dados do Personagem</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly =
            "readonly" } })
            </div>
        </div>
        <!-- Caixa de texto para edição -->
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <!--Fim da Caixa de texto para edição -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Salvar alterações" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Retornar", "Index")
</div>

RpgMvc/Views/Personagens/Index.cshtml
<!--Namespace da classe de Modelo para esta view-->
@model IEnumerable<RpgMvc.Models.PersonagemViewModel>


<!--Configuração para exibir mensagem de sucesso -->
@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Mensagem"]</div>
}
<!--Configuração para exibir mensagem de erro -->
@if (@TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]</div>
}

@{ViewBag.Title = "Personagens"; }<!--Título da página para o navegador-->
<h2>Relação de Personagens</h2> <!--Título da página-->
<p>

    <!--Links apontando para views na mesma pasta-->
    @Html.ActionLink("Criar Novo Personagem", "Create")
</p>
<table class="table">
    <tr>
        <!--Títulos das colunas da tabela-->
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
        <th>@Html.DisplayNameFor(model => model.Classe)</th>
        <th>@Html.DisplayNameFor(model => model.Disputas)</th>
        <th>@Html.DisplayNameFor(model => model.Vitorias)</th>
        <th>@Html.DisplayNameFor(model => model.Derrotas)</th>
        <th></th>
    </tr>
    <!--Looping para escrever os dados na tabela-->
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
            <td>@Html.DisplayFor(modelItem => item.Classe)</td>
            <td>@Html.DisplayFor(modelItem => item.Disputas )</td>
            <td>@Html.DisplayFor(modelItem => item.Vitorias)</td>
            <td>@Html.DisplayFor(modelItem => item.Derrotas)</td>
            <td>
                <!--Coluna para Links/botões-->
                @Html.ActionLink("Editar", "Edit", new { id = item.Id } ) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id }
                , new { onclick = "return confirm('Deseja realmente deletar?');"}) |

                @Html.ActionLink("Listar Habilidades", "Index", "PersonagemHabilidades", new {id = item.Id}) |
                @Html.ActionLink("Atribuir Habilidade", "Create", "PersonagemHabilidades", new {id = item.Id, nome = item.Nome})
            </td>
        </tr>
    }
</table>

@Html.ActionLink("Clique aqui para um embate com armas!", "Index", "Disputas",
null, new { @class = "btn btn-warning"})

 @Html.ActionLink("Clique aqui para um embate com habilidades!!!", "IndexHabilidades", "Disputas",
null, new { @class = "btn btn-dark" })

@Html.ActionLink("Clique aqui para um embate em grupo!!!", "DisputaGeral", "Disputas",
null, new { @class = "btn btn-danger" })